required_sections = ["system", "interfaces", "filter"]
rule_required_fields = ["interface"]
gateway_required_fields = ["name", "interface", "gateway"]
route_required_fields = ["network"]
route_required_any_fields = ["gateway", "interface"]
bridge_require_members = true
deprecated_sections = []
